restructure gandling result

diff --git a/.github/workflows/handle-results-test.yml b/.github/workflows/handle-results-test.yml
--- a/.github/workflows/handle-results-test.yml
+++ b/.github/workflows/handle-results-test.yml
@@ -11,15 +11,12 @@ jobs:
         run: |
           echo "Event '${{ github.event.action }}' received from '${{ github.event.client_payload.repository }}'"
           echo "Payload:  '${{ toJSON(github.event.client_payload) }}'"
-      - name: Handle Results Tests
+      - name: Display Result
         if: github.event.action == 'my-result'
         run: |
           echo "Test result received"
-          echo "Repository '${{ github.event.client_payload.repository }}' "
-          echo "Tryout  ${{github.event.client_payload.result}}"
-          if [success != ${{github.event.client_payload.result}}]; then
-            echo "Test Failed"
-            exit 1
-          else
-            echo "Test passed"
-          fi
+          echo "Repository: '${{ github.event.client_payload.repository }}' "
+          echo "Error results: '${{ github.event.client_payload.resultUrl }}' "
+      - name: Handle results failures
+        if: github.event.action == 'my-result' AND !${{github.event.client_payload.result == success}}
+        run:  exit 1
